### ISSUE TITLE
ImportError: cannot import name 'openai_object' from 'openai'

### ISSUE THREAD

**Issue by Yazdi9** [Kent0n-Li/ChatDoctor#55]
Traceback (most recent call last):
  File "/content/ChatDoctor/train.py", line 25, in <module>
    import utils
  File "/content/ChatDoctor/utils.py", line 15, in <module>
    from openai import openai_object
ImportError: cannot import name 'openai_object' from 'openai' (/usr/local/lib/python3.10/dist-packages/openai/__init__.py)
Traceback (most recent call last):
  File "/content/ChatDoctor/train.py", line 25, in <module>
    import utils
  File "/content/ChatDoctor/utils.py", line 15, in <module>
    from openai import openai_object
ImportError: cannot import name 'openai_object' from 'openai' (/usr/local/lib/python3.10/dist-packages/openai/__init__.py)
Traceback (most recent call last):
  File "/content/ChatDoctor/train.py", line 25, in <module>
    import utils
  File "/content/ChatDoctor/utils.py", line 15, in <module>
    from openai import openai_object
ImportError: cannot import name 'openai_object' from 'openai' (/usr/local/lib/python3.10/dist-packages/openai/__init__.py)
Traceback (most recent call last):
  File "/content/ChatDoctor/train.py", line 25, in <module>
    import utils
  File "/content/ChatDoctor/utils.py", line 15, in <module>
    from openai import openai_object
ImportError: cannot import name 'openai_object' from 'openai' (/usr/local/lib/python3.10/dist-packages/openai/__init__.py)
[2024-02-09 11:04:21,257] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 14644) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/content/ChatDoctor/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-02-09_11:04:21
  host      : 10ca0fca3068
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 14645)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-02-09_11:04:21
  host      : 10ca0fca3068
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 14646)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-02-09_11:04:21
  host      : 10ca0fca3068
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 14647)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-09_11:04:21
  host      : 10ca0fca3068
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 14644)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by kkk935208447** [comment]
更换openai的版本，我的问题就这样解决了
pip install openai==0.28.0
